### ISSUE TITLE
The transformBundle hook used by plugin babel-minify is deprecated.

### ISSUE THREAD

**Issue by ealmansi** [Comandeer/rollup-plugin-babel-minify#145]
I'm currently getting the following warning when running rollup-plugin-babel-minify:

```
(!) babel-minify plugin: The transformBundle hook used by plugin babel-minify is deprecated. The renderChunk hook should be used instead.
```

Further information:
- rollup-plugin-babel-minify@6.2.0
- rollup@1.1.0
- node v10.14.2
- npm v6.4.1
- Ubuntu 18.04.1 LTS

**Comment by ealmansi** [comment]
Likely related: https://github.com/egoist/rollup-plugin-hashbang/issues/1

**Comment by Comandeer** [comment]
Thx for the report, I'm already working on the fix. It should be finished this week.

**Comment by Comandeer** [comment]
The new version, 7.0.0, has been just published. It should fix this issue.
