### ISSUE TITLE
[bug] inList missing setter

### ISSUE THREAD

**Issue by WTDuck** [Comandeer/rollup-plugin-babel-minify#193]
As part of this Babel recent fix : https://github.com/babel/babel/commit/0f949990c33cc3c2b3dc24632f7639be166756b2

Solution: update babel to latest v7.7.1

**Comment by WTDuck** [comment]
It appears that an update isn't enough 🤔

**Comment by Comandeer** [comment]
Seems like this fix has not been released yet :thinking:

**Comment by Comandeer** [comment]
Fix for this issue was released as 9.1.1.
