### ISSUE TITLE
Name Change

### ISSUE THREAD

**Issue by boopathi** [Comandeer/rollup-plugin-babel-minify#47]
Babili is renamed to babel-minify Ref: https://github.com/babel/minify/issues/124 

+ [ ] Change name to rollup-plugin-babel-minify
+ [ ] Publish to npm after babel-minify is published. I have the name rollup-plugin-babel-minify on npm.

**Comment by Comandeer** [comment]
Quite strange decision IMO – I liked Babili. But let's do it, just to be coherent!

**Comment by Comandeer** [comment]
Ok, I've prepared branch `t/47` with all needed changes. I'll merge it to the `master` after official release of `babel-preset-minify`.

It'd be also nice if I've got publish rights to `rollup-plugin-babel-minify`.

**Comment by boopathi** [comment]
npm access grant: done

**Comment by Comandeer** [comment]
Ok, merged to `master`. I'll publish package later today.

**Comment by boopathi** [comment]
Cool. Thanks.

**Comment by Comandeer** [comment]
Published!
